### ISSUE TITLE
Support localization of multiline strings

### ISSUE THREAD

**Issue by ghost** [zowe/zowe-explorer-vscode#545] opened 2020-02-25 15:02 UTC
The `localize` function provided by the `vscode-nls` module doesn't seem to support multiline strings. I've tried multiple ways of formatting multiline strings, like:
```javascript
localize("msgId", "line1" +
  "line2");
localize("msgId", `line1
line2`);
```
Any of these attempts at localizing multiline strings in source code result in an error at build time.

**Comment by stepanzharychevbroadcom** [comment] 2020-03-17 16:07
I've tested exactly what was suggested in the issue. From this configuration:
![Screenshot 2020-03-17 at 17 00 00](https://user-images.githubusercontent.com/60000150/76875620-18823100-6871-11ea-9d14-eefe4377a19e.png)
It produces proper multiline string without any issues in JS and changes new lines to spaces for VSCode system messages.
![Screenshot 2020-03-17 at 16 59 46](https://user-images.githubusercontent.com/60000150/76876059-ad852a00-6871-11ea-8d99-2e77b30162d1.png)

The alternative working way is:
![Screenshot 2020-03-17 at 17 06 10](https://user-images.githubusercontent.com/60000150/76876095-b70e9200-6871-11ea-8be3-3cd0791e27f0.png)
Produces similar results.

@jellypuno @Colin-Stone @zFernand0 I think we can close it.

**Comment by tjohnsonBCM** [comment] 2020-03-17 16:33
@stepanzharychevbroadcom Has it been tested that `npm run package` also runs successfully with multiline strings?

**Comment by stepanzharychevbroadcom** [comment] 2020-03-17 17:05
@tjohnsonBCM Build results with error due to vscode-nls-dev dependency, which cannot digest ES6 string as string literal for some reason.
I will spend some more time with this one trying to figure out if it's our setup is incorrect, but if it's not we can't do anything about it, because the problem is not on our side.

`src/extension.js(85,38): second argument of a localize call must be a string literal.
[17:59:33] 'internalNlsCompileTask' errored after 4.5 s
[17:59:33] Error: Failed to rewrite file: /Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/out/src/extension.js
    at formatError (/Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (events.js:333:22)
    at Gulp.EventEmitter.emit (domain.js:485:12)
    at Object.error (/Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/node_modules/once/once.js:25:25)
    at f (/Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/node_modules/once/once.js:25:25)
    at tryCatch (/Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/node_modules/async-done/index.js:24:15)
    at done (/Users/stepanzarycev/Documents/Projects/vscode-extension-for-zowe/node_modules/async-done/index.js:40:12)
[17:59:33] 'build' errored after 4.55 s
`

**Comment by VitGottwald** [comment] 2020-03-31 12:35
This looks like a limitation of vscode-nls-dev we are currently not able to address. Downgrading to ES5 would cause other problems - we use async/await a lot and this would convert all of the code into generators, require a polyfill and generally degrade development and debugging experience.

**Comment by VitGottwald** [comment] 2020-03-31 12:38
@tjohnsonBCM do you think we should make this a higher priority? If so I think we should have a broader discussion about how we do localisation.

**Comment by tjohnsonBCM** [comment] 2020-03-31 18:01
I don't necessarily think this issue should have higher priority than others which are already in milestones. However, I agree it may be good to have a broader discussion about how we do localization, as we have multiple issues with the Localization label.

On another note, it surprises me that the `vscode-nls-dev` package doesn't seem to be maintained much anymore and hasn't been updated to support ES6 syntax. It still seems to be the recommended method by Microsoft for adding i18n support to a VSCode extension (their [i18n sample](https://github.com/microsoft/vscode-extension-samples/tree/master/i18n-sample) still uses it).

**Comment by VitGottwald** [comment] 2020-03-31 21:19
@tjohnsonBCM I have not given much time yet to see how `vscode-nls-dev` works internally, but the idea of extracting strings from source code and massaging them for translation afterwards seems dubious to me. I believe localisation should be baked in the architecture and explicit in code.

**Comment by phaumer** [comment] 2020-04-01 00:15
Isn't the danger to make the string non-translatable to other languages? I see examples where strings were fragmented (e.g. in Line 167 in DatasetTree.ts, initializeFavorites.error.profile1), which will make will make it hard to translate as differences in grammar will result into fragments of different length or even empty ones in other languages. If the multi-line layout fits in one language it might not fit in another.

**Comment by JillieBeanSim** [comment] 2024-05-03 14:19
This would be an enhancement request, removing bug label.  We have started work on a new localization plan with the following:
We have adopted the newer [l10n](https://github.com/microsoft/vscode-l10n)
Also have WIP for [WIP Allow users to contribute translations with POEditor](https://github.com/zowe/zowe-explorer-vscode/pull/2894)
closing this issue also due to lack of activity for 4 years.

**Closed** 2024-05-03 14:19 UTC
Labels: Localization, priority-medium, severity-medium
