### ISSUE TITLE
ZE affecting multi select with VSC 1.87

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2798] opened 2024-03-22 12:13 UTC
**Describe the bug**

Not sure if we had a workaround for something that got fixed but hearing reports of Zowe Explorer causing issues with other extensions multi-select functionality and issue goes away with ZE disabled with VSC 1.87+, previous VSC versions work fine.  I was able to recreate the issue using the [VSC tree view sample](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample), below is video of steps for recreation using the sample.

**To Reproduce**

https://github.com/zowe/zowe-explorer-vscode/assets/49491949/b37e67c9-11bb-478f-b5a6-a7e4c8e640e0

**Expected behavior**

multi-select should work the same with or without ZE installed

**Desktop (please complete the following information):**

- OS: macOS
- Zowe Explorer Version: 2.15.1
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment] 2024-05-14 20:03
I looked into this a bit more and it seems like multi-select behavior is having some issues with the newer VS Code versions (see https://github.com/microsoft/vscode/issues/208802).

With previous versions of VS Code, this issue does not occur with Zowe Explorer and does not affect the tree view sample.

**Comment by JillieBeanSim** [comment] 2024-07-24 13:35
changed priority to medium with PR still open and VSC not seeing as high priority

**Comment by traeok** [comment] 2024-08-12 15:36
As Adam mentioned, this appears to be resolved - I cannot reproduce the issue in VSC 1.92. Closing as completed - we can reopen if the issue comes up again.

**Closed by traeok** 2024-08-12 15:36 UTC
Labels: bug, On-Hold, priority-medium, severity-medium

**Comment by sdearth** [comment] 2024-08-12 17:13
I'll second that - I've verified that 1.92 resolves the issue.
