### ISSUE TITLE
Additional problems after push of 10.2 version and subsequent refresh.

### ISSUE THREAD

**Issue by johntgatesjr** [zowe/zowe-explorer-vscode#3185] opened 2024-10-03 18:18 UTC
Describe the bug
A clear and concise description of what the bug or error is.

Steps to Reproduce

Connect to z/OS machine and open an existing Assembler PDS member.
Expected behavior

In addition to assembler macro libraries, all formatting is also lost on text and JCL PDS files.

Details

Mac/OS. 14.7

VS Code.
Version: 1.94.0 (Universal)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Zowe plugin.
Published
2018-08-29, 14:33:40
Last released
2024-10-01, 16:56:37
Last updated
2024-10-02, 12:49:49
Identifier
zowe.vscode-extension-for-zowe

Additional context
This is a sev 1 issue for us as this push has rendered key functions of the Zowe plugin unusable and left it completely broken with no ability to roll back the push of the 10/2 update.

**Comment by traeok** [comment] 2024-10-07 18:38
Hi @johntgatesjr,

Given the context of PDS members and file associations, this appears to be a duplicate of #3181.
I'll close this as a duplicate for now, but if you would like to add additional context to this issue or #3181, please feel free to do so.

Thanks!

**Closed by traeok** 2024-10-07 18:38 UTC
Labels: bug
