### ISSUE TITLE
zowe-explorer-api ProfilesCache holding onto stale service profile from extenders when it is deleted from team config

### ISSUE THREAD

**Issue by FrankSu1996** [zowe/zowe-explorer-vscode#2395] opened 2023-07-25 13:51 UTC
We are currently contributing our own zowe service profiles (type zOpenDebug) using zowe-explorer-api. Our code has it's own watchers set up on the team config files. However, when all profiles of type zOpenDebug are removed from the team config file, the ZE-api ProfilesCache will still contain the removed profile. Note that aside from this case, the ProfilesCache seems to work as expected when multiple zOpenDebug profiles are added/deleted. It's only when they are ALL removed, that this bug occurs.

1. Create a new zowe profile type using zowe-explorer-api. 
2. Create a zowe team config file if one isn't already present.
3. Delete All instances of the new profile type from the team config file. 
4. call ProfileCache.refresh(). Despite profiles being removed from team config file, ProfilesCache will still return a reference to a profile.

**Expected behavior**

The ProfileCache should return an empty list for the new zowe profile type if they are all removed from the team config

**Desktop (please complete the following information):**

- OS: Windows 11
- Zowe Explorer Version: we are using @zowe/zowe-explorer-api@2.8.0

**Comment by JillieBeanSim** [comment] 2024-01-16 13:38
Hey @FrankSu1996 would you mind letting us know the version of the Zowe Explorer API you experience the issue and when deleting the profile manually from the team config file is that also being removed from the defaults if labeled as default in the config file? Thanks

**Comment by FrankSu1996** [comment] 2024-01-16 13:44
currently using @zowe/zowe-explorer-api v2.12.0. It doesn't matter whether or not I remove the default line in the config file. The bug occurs regardless.

**Comment by traeok** [comment] 2024-03-20 15:04
Hi @FrankSu1996,

I ran some tests with the FTP extension to reproduce this issue. For context, I am using the latest version of Zowe Explorer, Zowe Explorer API, and the FTP extension (v2.15.1). I believe this bug is a side effect of using the `ProfilesCache.refresh` function before accessing data from the cache.

To test, I registered a test command in the FTP extension to print profiles, which grabs the `ProfilesCache` instance from the extender API and logs it to the console:

![image](https://github.com/zowe/zowe-explorer-vscode/assets/86500639/7b20330e-c7d5-4e68-ae7e-6c931ecbcc04)

I noticed that if I skip the usage of `ProfilesCache.refresh`, I can access the profiles as expected, and changes to the team config are handled as expected in the instance:

<details>
<summary>Click to toggle screenshot</summary>

The first printed output contains 2 zFTP profiles, while the second output does not.
The only change was the removal of those 2 zFTP profiles from the team config, which is reflected in the second output:

![image](https://github.com/zowe/zowe-explorer-vscode/assets/86500639/5b77df99-d42a-4049-a98b-12340ced5c06)
</details>

However, when I use `ProfilesCache.refresh` from the FTP extension, the `allProfiles` array is empty, even if I provide the API register. I believe this is because Zowe Explorer already refreshes its ProfilesCache instance when the team config is changed - because the instance is already shared to extensions through the `ZoweExplorerExtender` API, the extra `refresh` call is not required, and calling it causes the profiles to be removed from the cache.

Can you confirm that removing the call to `ProfilesCache.refresh` resolves your issue with the latest ZE API?

**Comment by traeok** [comment] 2024-03-20 16:13
> Taking out ProfilesCache.refresh() does not solve the issue. I attached a couple of screen recordings, one where I comment out the call to refresh(). In both cases, I'm logging out both ProfilesCache.allProfiles and ProfilesCache.getProfiles("zOpenDebug"). The results are pretty interesting.
> 
> Without Refresh: ProfilesCache.allProfiles properly removes the zOpenDebug profile, but ProfilesCache.getProfiles("zOpenDebug") still returns it.
> 
> With Refresh: Both ProfilesCache.getProfiles("zOpenDebug") and ProfilesCache.allProfiles contains the zOpenDebug profile. In addition, allProfiles seems to have duplicated every profile.

Thanks for the detailed follow-up. `getProfiles` uses a different data structure than `allProfiles`, and it looks like that structure is not being updated correctly to reflect recent updates to the team config. I'll look into resolving this and will release a fix as soon as possible.

**Comment by FrankSu1996** [comment] 2024-03-20 16:27
Thanks for the update, appreciate you looking into this. For us, it's important for us that ProfilesCache keeps the ability for clients to be able to refresh.

**Comment by traeok** [comment] 2024-04-02 19:33
Closed as completed in #2795

**Closed by traeok** 2024-04-02 19:33 UTC
Labels: bug, priority-medium, severity-medium
