### ISSUE TITLE
No UI indicator presented to end user after clicking "Pull from Mainframe"

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2484] opened 2023-09-28 17:51 UTC
**Describe the bug**

There is no indication that the "Pull from Mainframe" action is ongoing once a user clicks it. We should show some sort of indication, such as a status bar indicator, to keep end users up to date.

**To Reproduce**

1. Search for a data set
2. Right-click on a data set member -> "Pull from Mainframe"
3. Notice that no UI indicator appears.

**Expected behavior**

Users should see some indication that we are actively pulling data from the mainframe.

**Comment by zaidmstrr** [comment] 2023-11-16 06:08
Can I work on the issue.

**Comment by t1m0thyj** [comment] 2023-11-17 15:43
> Can I work on the issue.

@zaidmstrr Sure, I have assigned you to the issue, feel free to work on it 🙂

**Comment by Ash-2k3** [comment] 2024-04-14 15:05
Hi @t1m0thyj, can you please assign me this issue ? I'd love to work on it !

**Comment by t1m0thyj** [comment] 2024-04-15 13:20
@Ash-2k3 Sure, I have assigned you the issue since it has not been worked on for 6 months, feel free to work on it 🙂

**Comment by Ash-2k3** [comment] 2024-04-19 06:09
Thanks @t1m0thyj, I have started working on it and I began with setting things up in my local machine, I am facing trouble with populating dummy data sets. I tried following this wiki https://github.com/zowe/zowe-explorer-vscode/wiki/Developer-Setup#test-profile-data. But it didn't really help me. I'd appreciate any help on this, Thanks!

**Comment by t1m0thyj** [comment] 2024-04-19 14:06
@Ash-2k3 Currently the `testProfileData` is unused and the only integration tests we actively maintain are for Theia: https://github.com/zowe/zowe-explorer-vscode/wiki/Developer-Setup#run-zowe-explorer-regression-tests-for-theia

If you have made a fix locally and verified that unit tests are passing, then feel free to open a PR 🙂

**Comment by Ash-2k3** [comment] 2024-04-22 06:28
@t1m0thyj In that case, I think the wiki should be updated :). Anyways, I have opened a PR for this, but I am a bit skeptical about my approach since I couldn't really test my changes and also because I am new to this codebase, so I am not really used to coding pattern. But I do plan to get used to it overtime 😀. Thanks! 

And also is there any issue which you would suggest me to work on after PR of this one gets merged ?

**Closed** 2024-04-25 12:29 UTC
Labels: bug, good first issue, priority-low, severity-low
