### ISSUE TITLE
Can "Create a New Connection to z/OS" actually add the necessary information to the config file?

### ISSUE THREAD

**Issue by zdmullen** [zowe/zowe-explorer-vscode#1879] opened 2022-07-21 12:18 UTC
**Describe the bug**

I have a team config file that only has two services in it (Endevor and Endevor Bridge for Git). As such, I have no section for zOSMF or anything else. 

When I select "Create a New Connection to z/OS", it opens the config file and...that's it. I know I can go and find the information somewhere, but couldn't it provide the necessary profile type, properties, etc.?

**Comment by JillieBeanSim** [comment] 2024-04-08 17:17
closing as duplicate of https://github.com/zowe/zowe-explorer-vscode/issues/2265

**Closed by JillieBeanSim** 2024-04-08 17:17 UTC
Labels: question, priority-medium, v2-profiles
