### ISSUE TITLE
trying to create a new zosmf profile i now get "Error running command zowe.ds.addSession"

### ISSUE THREAD

**Issue by phil34130** [zowe/zowe-explorer-vscode#2800] opened 2024-03-24 15:46 UTC
trying to create a new zosmf profile i now get:
"Error running command zowe.ds.addSession: Cannot read properties of undefined (reading 'usingTeamConfig'). This is likely caused by the extension that contributes zowe.ds.addSession."
Error encountered when loading your Zowe config. Click "Show Config" for more details.
this behavior happens when my VSCODE session runs in Ubuntu (WSL2). i can no longer define a zosmf profile
if it runs locally 'not on a remote window' then i can define a profile.
This used to work in the past.
i'm running windows 10
VSCODE is lvl 1.87.2
zowe explorer extension is V2.15.1
any idea ?

**Comment by zFernand0** [comment] 2024-03-25 12:53
Hey @phil34130,
Personally I always run Zowe Explorer on Headless Ubuntu over Remote SSH and if I get this error, I'm able to find more info on the logs (either in the Zowe Explorer Output channel or the extension logs)

Could you share a bit more info? There may be something in the logs that might help here 😋 

Question: Did you recently update the version of Zowe Explorer (or other extensions) in your WSL2 env?
Or, did you recently update your version of VSCode? If so, what where you running before?

There are times that new versions of VSCode may cause virtualized and remote environment configurations to make extensions misbehave. Although we don't officially [support certain environments](https://docs.zowe.org/stable/user-guide/ze-usage#supported-operating-systems-environments-and-platforms) (virtualized and/or remote), I'm sure it will be useful to enhance our documentation once we find the root cause of this problem.

**Comment by phil34130** [comment] 2024-03-25 19:50
Hi Fernando,
yes i think both got updated, with VSCODE being updated without my requiring it in the 1rst place...can't remember what was the version before....
Can you tell me how to access the logs you mention ?
What is the meaning of 'Zowe Explorer on Headless Ubuntu over Remote SSH'. How do you enable this ?
thank you

**Comment by zFernand0** [comment] 2024-04-01 14:59
Hey @phil34130,

> Can you tell me how to access the logs you mention ?

In WSL, you can find ZE related logs under the following path:
- `~/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.1/logs/`

The other way to view them is by going to the Output Channel, but if the extension is not activating properly, you may not be able to find the Zowe Explorer channel
![image](https://github.com/zowe/zowe-explorer-vscode/assets/37381190/a3fcfe67-32d6-446d-b95b-6f77ece0bda4)


> What is the meaning of 'Zowe Explorer on Headless Ubuntu over Remote SSH'. How do you enable this ?

This is just the way I use Zowe Explorer, which is also a non-supported way of running it 😋 
There is no need to change your environment.

---

Have you seen these sort of errors before?
![image](https://github.com/zowe/zowe-explorer-vscode/assets/37381190/01d0e29f-c6a8-4f13-966e-e7d753eed25d)

If so, the link below may be useful. Keep in mind that some commands/steps may vary slightly for WSL.
- https://github.com/zowe/zowe-explorer-vscode/wiki/Usage-in-Remote-Environments

**Comment by phil34130** [comment] 2024-04-03 17:22
here is what i always get when i tery to create a new zosmf profile:
[2024/04/03 19:19:13.516] [WARN] [extension.js:21] [ProfInfoErr: Failed to initialize secure credential manager
	at T.<anonymous> (/home/philippe/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:28521)
	at Generator.throw (<anonymous>)
	at a (/home/philippe/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:15812)] {
  mDetails: {
    errorCode: 'LoadCredMgrFailed',
    msg: 'Failed to initialize secure credential manager',
    causeErrors: [Error: [keyring] "glib" library returned an error:
    
    "\"Cannot autolaunch D-Bus without X11 $DISPLAY\""] {
      code: 'GenericFailure'
    }
  },
  mMessage: 'Failed to initialize secure credential manager',
  mItemsInError: []
}
[2024/04/03 19:19:14.607] [ERROR] [extension.js:21] [ProfInfoErr: Failed to initialize secure credential manager
	at T.<anonymous> (/home/philippe/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:28521)
	at Generator.throw (<anonymous>)
	at a (/home/philippe/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.1/out/src/extension.js:90:15812)] {
  mDetails: {
    errorCode: 'LoadCredMgrFailed',
    msg: 'Failed to initialize secure credential manager',
    causeErrors: [Error: [keyring] "glib" library returned an error:
    
    "\"Cannot autolaunch D-Bus without X11 $DISPLAY\""] {
      code: 'GenericFailure'
    }
  },
  mMessage: 'Failed to initialize secure credential manager',
  mItemsInError: []
}

**Comment by zFernand0** [comment] 2024-04-09 14:33
It looks like you have to unlock the keyring before Zowe Explorer can start.
For me a nice little Ubuntu-like pop-up shows up asking for the password to unlock the keyring. But I prefer just unlocking the keyring manually and then just doing a `> Developer: Reload Window` from the command palette.

This might help.
If you copy the code below into your `~/.bashrc` or your `~/.bash_aliases` and then run `unlock_keyring` from within a terminal on WSL, you should be able to use Zowe Explorer after reloading the window 😋 

```bash
function setup_dbus() {
  # Source: https://x410.dev/cookbook/wsl/sharing-dbus-among-wsl2-consoles/
  if [ -z "$XDG_RUNTIME_DIR" ]; then
    export XDG_RUNTIME_DIR=/run/user/$(id -u)
  fi
  if [ ! -d "$XDG_RUNTIME_DIR" ]; then
    echo root | sudo -Svp ""
    sudo mkdir $XDG_RUNTIME_DIR && sudo chmod 700 $XDG_RUNTIME_DIR && sudo chown $(id -un):$(id -gn) $XDG_RUNTIME_DIR
    sudo service dbus start
    sudo -k
  fi

  local bus_file_path="$XDG_RUNTIME_DIR/bus"
  export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
  if [ ! -e "$bus_file_path" ]; then
      /usr/bin/dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
  fi
}
function unlock_keyring() {
  setup_dbus
  echo root | gnome-keyring-daemon -r --unlock -c secrets
  export GNOME_KEYRING_CONTROL=$XDG_RUNTIME_DIR/keyring
}
```

**Comment by phil34130** [comment] 2024-04-09 15:47
still get the same failure...
i have issue unlock_keyring in the terminal:
philippe@LAPTOP-EC65KLAE:~$ unlock_keyring
** Message: 17:43:01.775: Replacing daemon, using directory: /run/user/1000/keyring
GNOME_KEYRING_CONTROL=/run/user/1000/keyring
philippe@LAPTOP-EC65KLAE:~$ 

and when i try to defone a new zOSMF profile i get:

[2024/04/09 17:43:07.092] [WARN] [extension.js:21] [ProfInfoErr: Failed to initialize secure credential manager
	at T.<anonymous> (/home/philippe/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.2/out/src/extension.js:90:28521)
	at Generator.throw (<anonymous>)
	at a (/home/philippe/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.2/out/src/extension.js:90:15812)] {
  mDetails: {
    errorCode: 'LoadCredMgrFailed',
    msg: 'Failed to initialize secure credential manager',
    causeErrors: [Error: [keyring] "glib" library returned an error:
    
    "\"Cannot autolaunch D-Bus without X11 $DISPLAY\""] {
      code: 'GenericFailure'
    }
  },
  mMessage: 'Failed to initialize secure credential manager',
  mItemsInError: []
}
[2024/04/09 17:43:07.927] [ERROR] [extension.js:21] [ProfInfoErr: Failed to initialize secure credential manager
	at T.<anonymous> (/home/philippe/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.2/out/src/extension.js:90:28521)
	at Generator.throw (<anonymous>)
	at a (/home/philippe/.vscode-server/extensions/zowe.vscode-extension-for-zowe-2.15.2/out/src/extension.js:90:15812)] {
  mDetails: {
    errorCode: 'LoadCredMgrFailed',
    msg: 'Failed to initialize secure credential manager',
    causeErrors: [Error: [keyring] "glib" library returned an error:
    
    "\"Cannot autolaunch D-Bus without X11 $DISPLAY\""] {
      code: 'GenericFailure'
    }
  },
  mMessage: 'Failed to initialize secure credential manager',
  mItemsInError: []
}

**Comment by zFernand0** [comment] 2024-04-09 16:56
Hey @phil34130,
Are you in the OMP Slack space? 
https://join.slack.com/t/openmainframeproject/shared_invite/zt-2gf6tz16e-ISYGsup2LdJcEkochO4XDg

I think it would be better/faster if we discussed over Slack about some ideas.
And once we have come to a resolution, we can update this issue (and our wiki/doc) 😋

**Comment by JillieBeanSim** [comment] 2024-07-11 18:42
@zFernand0 was a solution found for the situation in Slack or is there further investigation needed?

**Comment by zFernand0** [comment] 2024-07-11 20:42
Hey, I'm afraid that I couldn't not find anything on the OMP slack (or my DMs) about this 😢 

At this point, I believe we could _soft_ close this issue and if the problem persists, I'm sure we can re-open and and the necessary documentation! 🥳

**Comment by zFernand0** [comment] 2024-07-12 14:46
Closing for now!
@phil34130, please feel free to reach out (either here or on slack) wen we will be more than happy to assist again! 🙏🏽

**Closed by zFernand0** 2024-07-12 14:46 UTC
Labels: bug, priority-medium, severity-medium
