### ISSUE TITLE
File keeps trying to be saved if not enough permissions

### ISSUE THREAD

**Issue by pablocarle** [zowe/zowe-explorer-vscode#2627] opened 2023-12-14 15:13 UTC
**Describe the bug**

If I open a file for modifying in USS and make a change, if I don't have permissions to do it it will fail with the correct message, but there doesn't seem to be a way to stop it after dismissing the error; closing the file in vscode should probably be enough, but currently closing the file doesn't prompt for unsaved changes nor it stops explorer from trying to save it again.

**To Reproduce**

1. Open file in USS explorer without write access for the user.
2. Try to save, confirm the failure is write authorization.
3. Close the file in vscode.

**Expected behavior**

- Closing the file should probably prompt for unsaved changes.
- Closing without saving should stop explorer from trying to save the file.

**Desktop (please complete the following information):**

- OS: MacOs
- Zowe Explorer Version: 2.13

**Comment by traeok** [comment] 2023-12-20 19:56
Hi @pablocarle,

Can you confirm whether you have the "Auto Save" feature enabled in VS Code?
If so, please provide the currently-selected option and the "Auto Save Delay" if using the `afterDelay` option.

Thanks!

**Comment by pablocarle** [comment] 2023-12-21 08:06
Hi @traeok 
Thank you for the reply. Yes I just verified and I had the autoSave feature in `onFocusChange`

**Comment by t1m0thyj** [comment] 2024-08-05 16:57
@pablocarle Could you test with the latest version of Zowe Explorer and let us know if you still see the issue? We've made some improvements recently to how unsaved files are handled when VS Code is closed (https://github.com/zowe/zowe-explorer-vscode/pull/2760).

**Comment by ibmrcruicks** [comment] 2024-09-18 10:31
just to confirm we are still seeing system log flooding from this with new installations of Zowe Explorer.

I see a fix didn't make it into 2.18.0 - will it be fixed in 2.18.1 or 3.0.0 ? 

Remember, I have several thousand beta-testers available - we can just post a requirement for users to update to specific release, and hopefully see immediate benefit

**Comment by ibmrcruicks** [comment] 2024-09-19 00:23
thanks Trae - looking forward to 3.0.0!

the annoying thing about this loop is if the userid causing the issue is revoked, the system log just gets flooded with

**Comment by ibmrcruicks** [comment] 2024-10-24 22:22
I see 2.18.1 is now slated for February next year. Did the fix make into 3.0.0 as promised?

I'm still see my syslog flooded with these repeated errors 3 weeks after 3.0.0 shipped and a week after z Open Editor started  supporting/shipping 3.0.0

**Comment by traeok** [comment] 2024-10-24 23:53
> I see 2.18.1 is now slated for February next year. Did the fix make into 3.0.0 as promised?
> 
> I'm still see my syslog flooded with these repeated errors 3 weeks after 3.0.0 shipped and a week after z Open Editor started supporting/shipping 3.0.0

In Zowe Explorer v3, Auto Save is toggled off for USS files and data sets in the event of a save error. When an error is encountered in v3, you'll have to manually save the next time you make changes. Once a save is successful, Auto Save for that resource is re-enabled. This behavior is enabled by VS Code now that Zowe Explorer integrates with their file system APIs. 

We plan to release a fix with v2.18.1 as well.

**Comment by ibmrcruicks** [comment] 2024-10-25 09:04
OK - so I should see a reduction in the problem as more users update to 3.0.*.

Why so long for 2.18.1?

**Comment by traeok** [comment] 2024-10-25 11:44
> Why so long for 2.18.1?

I believe this is because now that v2 is considered Long Term Support, we plan to align our v2 release dates with Zowe's official release cadence. The code freeze is scheduled for February 10th, 2025.

Here are the planned release dates for the remaining v2 patch releases:
https://github.com/zowe/community/blob/master/Project%20Management/Schedule/Zowe%20PI%20%26%20Sprint%20Cadence.md#2181

**Closed** 2024-12-17 16:37 UTC
Labels: bug, priority-medium, severity-medium
